nelmio_cors:
    defaults:
        origin_regex: true
        allow_origin: ['http://localhost:3000']
        allow_methods: ['GET', 'OPTIONS', 'POST', 'PUT', 'PATCH', 'DELETE']
        allow_headers: ['Content-Type', 'Authorization', 'X-Request-ID', 'X-Content-Type-Options', 'X-Frame-Options', 'X-XSS-Protection']
        expose_headers: ['Link']
        max_age: 3600
        allow_credentials: true
    paths:
        '^/api/':
            allow_origin: ['http://localhost:3000']
            allow_headers: ['X-Custom-Auth', 'Content-Type', 'Authorization', 'X-Request-ID', 'X-Content-Type-Options', 'X-Frame-Options', 'X-XSS-Protection']
            allow_methods: ['POST', 'PUT', 'GET', 'DELETE', 'OPTIONS']
            max_age: 3600
            allow_credentials: true
